### ISSUE TITLE
Using Simple-ESCp inside android project

### ISSUE THREAD

**Issue by billyjoker** [JockiHendry/simple-escp#13]
Hi JockiHendry, i'm just starting with your code, and it works like a charm as an independent project. My issue is that i'd like to add it to my android project, but it seems that your project is compiled with Java 1.8, and is not compatible with android, top level compliance for me is 1.6, so, is there any way in order to get it imported properly to my project?

Congratulations for your work, it is awesome!!!

**Comment by JockiHendry** [comment]
Hi Billy,

Thank for your feedback.  Unfortunately, I've tested this project only in Java 7.  But you should be able to recompile this project by performing the following steps:
1. Fork this project.
2. Change https://github.com/JockiHendry/simple-escp/blob/master/build.gradle#L20 into: `sourceCompatibility = 1.6`.
3. Make sure you are using Java 6 and your JAVA_HOME environment variable is pointing to Java 6 SDK.
4. Run the following command: `.\gradlew distzip`.
5. The generated binary is located at _build/distributions_.

If this project didn't use Java 7 specific features, it should be recompiled smoothly in Java 6.

**Comment by billyjoker** [comment]
Hi Jocki, thanks for your soon answer!! Finally i recompiled the project modifyng the classes to get them 1.6 compliance compatible. But it seems i'm doing something wronk because the execution throws me a class not found exception:
java.lang.NoClassDefFoundError: javax.json.JsonObject
But in fact the json jar it seems to be correctly included... Any idea?

I'll try following your steps, though now i have your project with 1.6

Thanks again.

**Comment by JockiHendry** [comment]
Do you mean you encountered this exception while running `gradlew distZip`?  If this is the case, try `gradlew clean ditZip` to clear the staging area before building the binary distribution.

Or, do you mean Gradle has produced a working binary, but you encountered this exception while running your application?  If this is the case, perhaps you didn't setup dependencies properly for your application.

**Comment by billyjoker** [comment]
I mean that Gradle has produced a working binary, but i've encountered the Json class not found exception. I've performed the steps as you said, with a command prompt, firstly gradlew clean distZip, and after that, gradlew distZip. it builds a working file, i attach you a picture with the build tree generated. then, i've imported the har file generated at lib folder, and i've checked the file inside order and export window. 

![simpleescp](https://cloud.githubusercontent.com/assets/4301306/4538846/fe5813a8-4df5-11e4-90e7-80f9ddafa211.png)

Do you have any idea? I also tried including the json jar files associated, and it throws a dalvik duplicate file exception, as if really the project recognizes the files......

Jocki, thanks for your patient!!

**Comment by billyjoker** [comment]
My command prompt...

![cmd](https://cloud.githubusercontent.com/assets/4301306/4538897/7779445a-4df6-11e4-942d-0eb4c158ed0c.png)

**Comment by billyjoker** [comment]
And my logcat:

10-07 10:02:51.166: W/dalvikvm(1950): VFY: unable to find class referenced in signature (Ljavax/script/ScriptEngine;)
10-07 10:02:51.168: W/dalvikvm(1950): VFY: unable to resolve interface method 23354: Ljavax/script/ScriptEngine;.getBindings (I)Ljavax/script/Bindings;
10-07 10:02:51.170: W/dalvikvm(1950): Unable to resolve superclass of Lsimple/escp/fill/DataSourceBinding; (2807)
10-07 10:02:51.170: W/dalvikvm(1950): Link of class 'Lsimple/escp/fill/DataSourceBinding;' failed
10-07 10:02:51.177: E/dalvikvm(1950): Could not find class 'javax.json.JsonObject', referenced from method simple.escp.data.DataSources.<clinit>
10-07 10:02:51.177: W/dalvikvm(1950): VFY: unable to resolve const-class 2753 (Ljavax/json/JsonObject;) in Lsimple/escp/data/DataSources;
10-07 10:02:51.178: W/dalvikvm(1950): Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lsimple/escp/data/DataSources;
10-07 10:02:51.179: W/dalvikvm(1950): threadid=1: thread exiting with uncaught exception (group=0x410ba9a8)
10-07 10:02:51.182: E/AndroidRuntime(1950): FATAL EXCEPTION: main
10-07 10:02:51.182: E/AndroidRuntime(1950): java.lang.NoClassDefFoundError: javax.json.JsonObject
10-07 10:02:51.182: E/AndroidRuntime(1950):     at simple.escp.data.DataSources.<clinit>(DataSources.java:26)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at com.prv.pdf2jpg.MainActivity$2.onClick(MainActivity.java:181)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at android.view.View.performClick(View.java:4211)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at android.view.View$PerformClick.run(View.java:17456)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at android.os.Handler.handleCallback(Handler.java:725)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at android.os.Handler.dispatchMessage(Handler.java:92)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at android.os.Looper.loop(Looper.java:153)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at android.app.ActivityThread.main(ActivityThread.java:5293)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at java.lang.reflect.Method.invokeNative(Native Method)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at java.lang.reflect.Method.invoke(Method.java:511)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
10-07 10:02:51.182: E/AndroidRuntime(1950):     at dalvik.system.NativeStart.main(Native Method)

**Comment by JockiHendry** [comment]
It seems that you've produced a working binary.  It should work as expected in Java SE because that's exactly how I release the binary for each release.

In the generated zip file, you will find simple-escp jar file and required jar files.  You should add all of these files as dependency in your Android project by adding them to `libs` folder.  If you have problem with duplicate exception, try to clean your project first by selecting **Project**, **Clean** in Eclipse.  You should check all referenced Android libraries in your project for duplicated jar.  See http://tools.android.com/recent/dealingwithdependenciesinandroidprojects for information about dependencies in Android project.

Another problem is Dalvik doesn't completely compatible with Java SE.  For example, `javax.script` package (JSR-223) is available in Java SE 6.  Java SE 6 also shipped with Rhino as built-in JavaScript engine. But Dalvik doesn't have them.  If you want to enable scripting, you should add them manually as external JAR.  You can googling the google for more information :)

**Comment by billyjoker** [comment]
Yes, it seems to be the problem... anyway, i wonder if i could generate the esc-p commands through a filled json with no using datasource object, it could be?

**Comment by JockiHendry** [comment]
You can use `simple.escp.data.EmptyDataSource` (https://github.com/JockiHendry/simple-escp/blob/master/src/main/java/simple/escp/data/EmptyDataSource.java) for _'no datasource'_ purpose.
